#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPS_DIR="${ROOT_DIR}/.deps"
DOWNLOAD_DIR="${DEPS_DIR}/downloads"
PREFIX_DIR="${DEPS_DIR}/prefix"
SRC_DIR="${DEPS_DIR}/src"
BIN_DIR="${DEPS_DIR}/bin"

NODE_VERSION="${NODE_VERSION:-20.11.1}"
ONNXRUNTIME_VERSION="${ONNXRUNTIME_VERSION:-1.16.0}"
DROGON_REF="${DROGON_REF:-v1.9.0}"
OPEN5GS_REF="${OPEN5GS_REF:-v2.7.7}"
UBUNTU_MIRROR="${UBUNTU_MIRROR:-http://archive.ubuntu.com/ubuntu}"

mkdir -p "${DOWNLOAD_DIR}" "${PREFIX_DIR}" "${SRC_DIR}" "${BIN_DIR}"

log() { printf '\033[1;36m[kylin-install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[kylin-install]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31m[kylin-install]\033[0m %s\n' "$*" >&2; exit 1; }

as_root() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

download() {
  local url="$1"
  local out="$2"
  if [[ -s "${out}" ]]; then
    return 0
  fi
  log "download ${url}"
  if command -v curl >/dev/null 2>&1; then
    curl -fL --retry 3 --connect-timeout 20 -o "${out}" "${url}"
  elif command -v wget >/dev/null 2>&1; then
    wget -O "${out}" "${url}"
  else
    die "curl/wget 均不存在，无法下载依赖"
  fi
}

install_apt_packages() {
  command -v apt-get >/dev/null 2>&1 || die "未找到 apt-get；请确认系统为银河麒麟 v10 桌面版或兼容 Debian 的发行版"
  log "安装系统依赖包"
  as_root apt-get update
  as_root apt-get install -y \
    build-essential cmake make ninja-build pkg-config git curl wget ca-certificates \
    gnupg lsb-release unzip tar xz-utils jq lsof procps net-tools iproute2 iputils-ping \
    python3 python3-venv python3-pip python3-dev \
    libssl-dev libjsoncpp-dev uuid-dev zlib1g-dev libsqlite3-dev \
    nlohmann-json3-dev libspdlog-dev \
    libbrotli-dev libyaml-cpp-dev \
    docker.io

  if command -v systemctl >/dev/null 2>&1; then
    as_root systemctl enable --now docker || warn "Docker 服务启动失败，请稍后手动执行：sudo systemctl enable --now docker"
  fi

  if getent group docker >/dev/null 2>&1 && [[ -n "${USER:-}" ]]; then
    as_root usermod -aG docker "${USER}" || true
  fi
}

major_version() {
  "$1" --version 2>/dev/null | sed -E 's/^v?([0-9]+).*/\1/' || true
}

ensure_node() {
  local use_system=0
  if command -v node >/dev/null 2>&1; then
    local major
    major="$(major_version node)"
    if [[ "${major:-0}" -ge 18 ]]; then
      use_system=1
    fi
  fi
  if [[ "${use_system}" == "1" ]]; then
    log "使用系统 Node.js: $(node --version)"
    return 0
  fi

  local name="node-v${NODE_VERSION}-linux-x64"
  local archive="${DOWNLOAD_DIR}/${name}.tar.xz"
  download "https://nodejs.org/dist/v${NODE_VERSION}/${name}.tar.xz" "${archive}"
  rm -rf "${DEPS_DIR}/${name}"
  tar -xJf "${archive}" -C "${DEPS_DIR}"
  ln -sf "${DEPS_DIR}/${name}/bin/node" "${BIN_DIR}/node"
  ln -sf "${DEPS_DIR}/${name}/bin/npm" "${BIN_DIR}/npm"
  ln -sf "${DEPS_DIR}/${name}/bin/npx" "${BIN_DIR}/npx"
  export PATH="${BIN_DIR}:$PATH"
  log "已安装项目内 Node.js: $("${BIN_DIR}/node" --version)"
}

ensure_onnxruntime() {
  local dir="${DEPS_DIR}/onnxruntime-linux-x64-${ONNXRUNTIME_VERSION}"
  if [[ -f "${dir}/include/onnxruntime_cxx_api.h" && -f "${dir}/lib/libonnxruntime.so" ]]; then
    log "ONNX Runtime 已存在: ${dir}"
    return 0
  fi
  local archive="${DOWNLOAD_DIR}/onnxruntime-linux-x64-${ONNXRUNTIME_VERSION}.tgz"
  download "https://github.com/microsoft/onnxruntime/releases/download/v${ONNXRUNTIME_VERSION}/onnxruntime-linux-x64-${ONNXRUNTIME_VERSION}.tgz" "${archive}"
  rm -rf "${dir}"
  tar -xzf "${archive}" -C "${DEPS_DIR}"
  [[ -f "${dir}/lib/libonnxruntime.so" ]] || die "ONNX Runtime 解压后缺少 libonnxruntime.so"
  log "已安装 ONNX Runtime: ${dir}"
}

ensure_drogon() {
  if [[ -d "${PREFIX_DIR}/lib/cmake/Drogon" || -d "${PREFIX_DIR}/lib64/cmake/Drogon" ]]; then
    log "Drogon 已存在: ${PREFIX_DIR}"
    return 0
  fi
  log "构建 Drogon ${DROGON_REF}"
  rm -rf "${SRC_DIR}/drogon"
  git clone --recursive --depth 1 --branch "${DROGON_REF}" https://github.com/drogonframework/drogon.git "${SRC_DIR}/drogon"
  cmake -S "${SRC_DIR}/drogon" -B "${SRC_DIR}/drogon/build" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="${PREFIX_DIR}" \
    -DBUILD_CTL=OFF \
    -DBUILD_EXAMPLES=OFF
  cmake --build "${SRC_DIR}/drogon/build" -j"$(nproc)"
  cmake --install "${SRC_DIR}/drogon/build"
}

write_env_file() {
  local onnx_dir="${DEPS_DIR}/onnxruntime-linux-x64-${ONNXRUNTIME_VERSION}"
  cat > "${ROOT_DIR}/.env.kylin" <<EOF
# Generated by scripts/kylin_v10_install_deps.sh
export SFC_ROOT="${ROOT_DIR}"
export SFC_DEPS_DIR="${DEPS_DIR}"
export PATH="${BIN_DIR}:\$PATH"
export ONNXRUNTIME_DIR="${onnx_dir}"
export CMAKE_PREFIX_PATH="${PREFIX_DIR}:${onnx_dir}:\${CMAKE_PREFIX_PATH:-}"
export LD_LIBRARY_PATH="${PREFIX_DIR}/lib:${PREFIX_DIR}/lib64:${onnx_dir}/lib:\${LD_LIBRARY_PATH:-}"
export SFC_SATELLITE_IMAGE_AMD64="docker.1ms.run/gradiant/open5gs:2.7.7"
export SFC_SATELLITE_DOCKERFILE="${ROOT_DIR}/docker/open5gs-satellite.Dockerfile"
export SFC_SATELLITE_BUILD_CONTEXT="${ROOT_DIR}"
export SFC_SATELLITE_PLATFORM=""
export UERANSIM_IMAGE="docker.io/free5gc/ueransim:latest"
export SFC_MYSQL_DISABLE_BINLOG=1
export SFC_TRUNCATE_RUN_LOGS_ON_START=1
EOF
  log "已写入环境文件: ${ROOT_DIR}/.env.kylin"
}

install_frontend_deps() {
  log "安装前端 npm 依赖"
  (cd "${ROOT_DIR}/frontend" && npm ci)
}

main() {
  install_apt_packages
  ensure_node
  ensure_onnxruntime
  ensure_drogon
  write_env_file
  # shellcheck disable=SC1091
  source "${ROOT_DIR}/.env.kylin"
  install_frontend_deps
  "${ROOT_DIR}/scripts/kylin_v10_prepare_images.sh" || warn "容器镜像准备未完全成功；可稍后重新执行 scripts/kylin_v10_prepare_images.sh"
  log "依赖安装完成。若当前用户刚加入 docker 组，请注销/重新登录，或执行 newgrp docker 后再启动系统。"
}

main "$@"
